### ISSUE TITLE
Licensing/Permissions?

### ISSUE THREAD

**Issue by JTacoCSharpie** [Levi2229/UpgradeEquipment#2]
Howdy, I'm a fan of your mod and I've been using it in almost every playthrough since I found it.

I'm going into my first forays into modding and I took the recent break between calamity and UE as a good excuse to learn how mods work: I'd like to make my first mod one that's intended to work almost identically to Equipment Upgrader but with alternate balance, broader features, and generally broader mod support. Because I want to make mine so similar in concept I'd like permission before posting it (though any posting may be a way's out yet since I'm currently still learning.)

I've crossposted to both your terraria forum profile & github. Apologies but I didn't know which one you check as from what I can tell your git puts your last activity at near half a year and your profile was last seen at over a year ago. I've included a link to my steam profile for more expedient contact in the other crosspost and an extra bit about friend requests,

**Comment by Levi2229** [comment]
Hey, feel free to use any and all parts of this mod! You have my permission, best of luck.
